export class TabConstants {
  static readonly home_constants: number = 0;
  static readonly knowledge_constants: number = 1;
  static readonly wechat_constants: number = 2;
  static readonly navigation_constants: number = 3;
  static readonly project_constants: number = 4;

  static readonly home_key:string = 'home';
  static readonly knowledge_key:string = 'knowledge';
  static readonly wechat_key:string = 'wechat';
  static readonly navigation_key:string = 'shop';
  static readonly project_key:string = 'project';
}